"""Drift guard: Python and TypeScript SAFE_MODIFIER_TOKENS must stay identical.

The MCP layer validates corrective text generated by the Python FHIR facade.
If Python emits a modifier token Node does not know, Node falls back to a
generic message and the useful corrective text is silently lost.

Issue #156 — nothing in CI previously failed when the two allowlists diverged.
"""

from __future__ import annotations

import re
from pathlib import Path

from r6.routes import _SAFE_MODIFIER_TOKENS

REPO_ROOT = Path(__file__).resolve().parents[1]
TS_BACKEND_FAILURE = (
    REPO_ROOT
    / "services"
    / "agent-orchestrator"
    / "src"
    / "backend-failure.ts"
)


def _extract_ts_safe_modifier_tokens(source: str) -> set[str]:
    """Parse SAFE_MODIFIER_TOKENS string literals from backend-failure.ts.

    Expects a ``const SAFE_MODIFIER_TOKENS = new Set([ ... ]);`` block with
    double-quoted string entries (current house style). Formatting changes that
    break the regex should fail the test with a clear message rather than
    silently returning an empty set.
    """
    match = re.search(
        r"const\s+SAFE_MODIFIER_TOKENS\s*=\s*new\s+Set\(\s*\[(.*?)\s*\]\s*\)\s*;",
        source,
        re.DOTALL,
    )
    if not match:
        raise AssertionError(
            "Could not find `const SAFE_MODIFIER_TOKENS = new Set([...]);` in "
            f"{TS_BACKEND_FAILURE.relative_to(REPO_ROOT)}. Update the drift "
            "parser if the TypeScript declaration shape changed."
        )
    body = match.group(1)
    tokens = set(re.findall(r'"([^"\\]*(?:\\.[^"\\]*)*)"', body))
    if not tokens:
        raise AssertionError(
            "Parsed SAFE_MODIFIER_TOKENS block but found no string literals — "
            "check quoting style in backend-failure.ts."
        )
    return tokens


def test_safe_modifier_tokens_match_python_and_typescript():
    """Python _SAFE_MODIFIER_TOKENS and TS SAFE_MODIFIER_TOKENS must be equal."""
    assert TS_BACKEND_FAILURE.is_file(), (
        f"Missing TypeScript source: {TS_BACKEND_FAILURE}"
    )
    ts_tokens = _extract_ts_safe_modifier_tokens(
        TS_BACKEND_FAILURE.read_text(encoding="utf-8")
    )
    py_tokens = set(_SAFE_MODIFIER_TOKENS)

    only_in_python = sorted(py_tokens - ts_tokens)
    only_in_typescript = sorted(ts_tokens - py_tokens)

    assert not only_in_python and not only_in_typescript, (
        "SAFE_MODIFIER_TOKENS allowlists drifted between Python and TypeScript.\n"
        f"  only in Python (r6/routes.py): {only_in_python}\n"
        f"  only in TypeScript (backend-failure.ts): {only_in_typescript}\n"
        "Keep both lists identical so MCP does not drop specific corrective "
        "messages for unknown modifier tokens."
    )


def test_safe_modifier_tokens_parser_rejects_missing_block():
    """Parser failure mode: missing Set block surfaces a useful AssertionError."""
    try:
        _extract_ts_safe_modifier_tokens("export const unrelated = 1;\n")
    except AssertionError as exc:
        assert "Could not find" in str(exc)
    else:
        raise AssertionError("expected AssertionError for missing token block")
