"""Fasten model column widths — external ids must fit real-world values.

SQLite ignores VARCHAR length, so an under-width column passes every test
here and then raises StringDataRightTruncation on Postgres the first time a
long external id arrives (same class of bug as
tests/test_ingest_resilience.py::test_resource_id_column_fits_real_ehr_ids
and tests/actions/test_state_transitions.py::
test_status_column_fits_every_legal_state — this repo has been bitten three
times). Fasten mints org_connection_id/task_id; we do not control their
length, so every column that stores an EXTERNAL id must be at least 255.

tenant_id is internally generated and intentionally stays at 64 — it is NOT
in the external-id set below.
"""
from types import SimpleNamespace

from sqlalchemy import Column, MetaData, String, Table

from r6.fasten.models import FastenConnection, FastenJob

# Minimum width for any column holding an id minted by an external system.
EXTERNAL_ID_MIN_WIDTH = 255

# Every (model, column) pair on the Fasten models that stores an id we do
# not generate ourselves. Computed into one parametrized-style loop so a new
# external-id column only needs to be added here, not a new hand-rolled test.
_EXTERNAL_ID_COLUMNS = (
    (FastenConnection, 'org_connection_id'),  # PK — minted by Fasten
    (FastenJob, 'task_id'),                   # minted by Fasten
    (FastenJob, 'org_connection_id'),         # minted by Fasten
)


def test_external_id_columns_fit_external_ids():
    for model, col_name in _EXTERNAL_ID_COLUMNS:
        col = model.__table__.c[col_name]
        assert col.type.length >= EXTERNAL_ID_MIN_WIDTH, (
            f'{model.__tablename__}.{col_name} is VARCHAR({col.type.length}) '
            f'— external ids need >= {EXTERNAL_ID_MIN_WIDTH}. SQLite masks '
            f'this; Postgres truncation-errors mid-ingest.'
        )


def test_tenant_id_stays_internal_width():
    # tenant_id is generated by us; widening it is not needed and keeping it
    # at 64 documents that it is NOT an external id.
    assert FastenConnection.__table__.c.tenant_id.type.length == 64
    assert FastenJob.__table__.c.tenant_id.type.length == 64


class _FakeConn:
    def __init__(self, sink):
        self._sink = sink

    def execute(self, stmt):
        self._sink.append(str(stmt))

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False


class _FakeEngine:
    """Just enough engine for reconcile_schema's widen path."""
    dialect = SimpleNamespace(name='postgresql')

    def __init__(self):
        self.executed = []

    def begin(self):
        return _FakeConn(self.executed)


class _FakeInspector:
    def __init__(self, tables):
        self._tables = tables

    def get_table_names(self):
        return list(self._tables)

    def get_columns(self, name):
        return self._tables[name]


def test_schema_sync_widens_primary_key_columns(monkeypatch):
    """schema_sync's auto-widen must NOT exclude PK columns.

    fasten_connections.org_connection_id is a PRIMARY KEY; widening a
    varchar PK on Postgres is still a plain online type widen. If
    reconcile_schema ever skipped PKs, the model widen would never reach
    long-lived deployments and long Fasten ids would truncation-error.
    """
    import r6.schema_sync as schema_sync

    md = MetaData()
    Table('fasten_connections_pk_probe', md,
          Column('org_connection_id', String(EXTERNAL_ID_MIN_WIDTH),
                 primary_key=True))
    live = {'fasten_connections_pk_probe': [
        {'name': 'org_connection_id', 'type': String(64)},
    ]}
    monkeypatch.setattr(schema_sync, 'inspect',
                        lambda engine: _FakeInspector(live))

    engine = _FakeEngine()
    added = schema_sync.reconcile_schema(engine, md)

    expected = (
        'ALTER TABLE fasten_connections_pk_probe '
        f'ALTER COLUMN org_connection_id TYPE VARCHAR({EXTERNAL_ID_MIN_WIDTH})'
    )
    assert expected in added, (
        'reconcile_schema did not widen a PRIMARY KEY column — PK columns '
        f'must not be excluded from auto-widen. Executed: {added}'
    )
    assert expected in engine.executed
